### ISSUE TITLE
Determine why chairs are not working properly

### ISSUE THREAD

**Issue by jenreiher** [agenda-item/agenda-item#102]

**Comment by monicamow** [comment]
- while looking at this with @jleeisme before demo day, his code seemed to be identical to mover/seconder...has something to do with the post request in actions.rb sending the json back to the front end (the chair was successfully updated in back end and saved to db)

**Comment by jenreiher** [comment]
ah! perhaps the front end needed the same tweak that we ran up against with the Object, object thing.

**Comment by monicamow** [comment]
did we ever look into this?

**Comment by jenreiher** [comment]
no - I don't think so, but it could be similar to the _.user thing that we needed to do for attendees?

**Comment by monicamow** [comment]
OK I read the comment from above...seems like a JSON issue

**Comment by monicamow** [comment]
@jen please see my 'fix-the-chair' branch and assist with showing the chair's name on the front end. currently, it only shows the user id because I do not know how to properly sync the meeting details and the chair user object to extract the name

**Comment by jen** [comment]
Hi! Wrong Jen.

. . . . . . . . . . . . . . . . . . . . . . . .

Industry: Visual / Interface Design + Development

1459 18th Street #131 San Francisco CA 94107

415 552 3111  industrious.com

Full strength design -- no animal testing
