### ISSUE TITLE
Fix the logging of chair, mover, seconder, etc.

### ISSUE THREAD

**Issue by monicamow** [agenda-item/agenda-item#146]
All the other fields in the meeting details or agenda item are cleared when a new user is logged/clicked. I think when the user is logged (on selection when the post request is triggered), the post request update in the back is updating all the other fields with empty information. 

I *think* I know how to fix it though.

We need to add a nil check for each parameter in the params hash. The field will post/update only if the params[:field_item] isn't nil.

**Comment by jenreiher** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9990876-177428397_3-s4-v1.png?transparent=1&width=246)
