### ISSUE TITLE
Adjust the meetings routes to only show the current organization

### ISSUE THREAD

**Issue by jenreiher** [agenda-item/agenda-item#94]
Now that Demo Day is over and we might have more than one user... 
- [ ] add sessions for the current organization

- [ ] adjust the /api/meeting routes to query for the current session

**Comment by monicamow** [comment]
yes, this is what I meant by #90 (I guess they are organization sessions, but with a current user?)

**Comment by jenreiher** [comment]
@monicamow look at the code I pushed in the helpers do section of the actions.rb: https://github.com/agenda-item/agenda-item/blob/master/app/actions.rb

I am thinking like that, but for the current organization?

**Comment by monicamow** [comment]
@jenreiher right, but it's only the user that created that organization (until multi user implemented) that can log into that org and write things. and an org doesn't have a password, so wouldn't a user still need to log in. I think it needs to be user login -> redirect to an org session as well?

**Comment by jenreiher** [comment]
@monicamow yes, they would need to login as the user, but I think it could set their org session at that time. my thought is that if we design it to be org-specific now we don't have to change the code again when we launch the rest later ;) 
we'll need it for when we do the "where" queries

**Comment by jenreiher** [comment]
@monicamow talk to me more about how you were picturing it? maybe you're seeing something I am not

**Comment by monicamow** [comment]
now that I think about it instead of user login -> redirect to user's org ... I agree with you that it can be done together (set org session when user logs in) @jenreiher

**Comment by jenreiher** [comment]
@monicamow will definitely require #90 first! I agree.
